language: python

python:
 - 2.7
 - pypy

matrix:
  allow_failures:
    - python: pypy

install:
  - python setup.py install
  - pip install --use-mirrors nose

script:
  - nosetests -v tests/unit


notifications:
  email:
    - ed.leafe@rackspace.com
  irc: "irc.freenode.org#rackspace-dev"
